import { defineConfig, devices } from '@playwright/test';

const STORYBOOK_PORT = process.env['STORYBOOK_PORT'] ?? '6006';
const STORYBOOK_URL = `http://localhost:${STORYBOOK_PORT}`;

// @todo generated by ai, need to check it later
export default defineConfig({
  testDir: './tests',
  timeout: 30_000,
  expect: {
    timeout: 5_000,
  },
  fullyParallel: true,
  retries: process.env['CI'] ? 2 : 0,
  reporter: process.env['CI'] ? 'github' : 'list',
  use: {
    baseURL: `${STORYBOOK_URL}/iframe.html`,
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: {
    command: `npm run storybook -- --ci --port ${STORYBOOK_PORT}`,
    url: `${STORYBOOK_URL}/iframe.html`,
    reuseExistingServer: !process.env['CI'],
    timeout: 120_000,
  },
});
